import { auth, db } from "./firebase-config.js";
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { doc, getDoc, setDoc, deleteDoc, collection, getDocs, query, orderBy, serverTimestamp, Timestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const OWNER_EMAILS = ["silva12.anderson@gmail.com"];
let activeTab = "sales";
let requestsCache = [];
let accessCache = [];

function normalizeEmail(value){ return String(value || "").trim().toLowerCase(); }
function normalizeTag(value){ const cleaned = String(value || "").trim().toUpperCase().replace(/\s+/g, ""); return cleaned.startsWith("#") ? cleaned : (cleaned ? `#${cleaned}` : ""); }
function planLabel(plan){ const p=String(plan||"trial").toLowerCase(); if(p==="basic") return "Básico"; if(p==="plus") return "Plus"; if(p==="premium") return "Premium"; return "Trial"; }
function addPlanDuration(plan, baseDate = new Date()){ const d = new Date(baseDate); const p=String(plan||"trial").toLowerCase(); if(p==="trial") d.setDate(d.getDate()+7); else if(p==="basic") d.setMonth(d.getMonth()+1); else if(p==="plus") d.setMonth(d.getMonth()+6); else if(p==="premium") d.setFullYear(d.getFullYear()+1); else d.setDate(d.getDate()+7); return d; }
function toDate(value){ if(!value) return null; if(value?.toDate) return value.toDate(); if(value?.seconds) return new Date(value.seconds*1000); const d=new Date(value); return Number.isNaN(d.getTime()) ? null : d; }
function formatDate(value){ const d=toDate(value); return d ? d.toLocaleDateString("pt-BR") : "—"; }
function statusBucket(item){ const status=String(item.status||"released").toLowerCase(); const expires=toDate(item.planExpiresAt); if(status==="blocked" || status==="expired" || status==="revoked") return "expired"; if(expires && expires < new Date()) return "expired"; if(String(item.plan||"").toLowerCase()==="trial") return "trial"; return "active"; }
function setPanelVisible(visible){ document.querySelector("#saasAccessDenied")?.setAttribute("hidden",""); const content=document.querySelector("#saasAdminContent"); if(content) content.hidden=!visible; }
function showGate(message=""){ const gate=document.querySelector("#saasLocalGate"); const error=document.querySelector("#saasGateError"); if(error) error.textContent=message; if(gate) gate.hidden=false; setPanelVisible(false); }
function hideGate(){ const gate=document.querySelector("#saasLocalGate"); if(gate) gate.hidden=true; setPanelVisible(true); }
async function canAccess(user){ if(!user) return false; if(OWNER_EMAILS.includes(normalizeEmail(user.email))) return true; try{ const userSnap=await getDoc(doc(db,"users",user.uid)); const data=userSnap.exists()?userSnap.data():{}; return Boolean(data.saasOwner||data.systemOwner||data.role==="systemOwner"); }catch{return false;} }
async function handleGate(){ const email=normalizeEmail(document.querySelector("#saasGateEmail")?.value); const password=String(document.querySelector("#saasGatePassword")?.value||""); const error=document.querySelector("#saasGateError"); const btn=document.querySelector("#saasGateBtn"); if(error) error.textContent=""; if(!OWNER_EMAILS.includes(email)){ if(error) error.textContent="E-mail admin não autorizado."; return; } if(!password){ if(error) error.textContent="Informe a senha do admin."; return; } try{ if(btn){btn.disabled=true;btn.textContent="Entrando...";} const credential=await signInWithEmailAndPassword(auth,email,password); if(!(await canAccess(credential.user))){ await signOut(auth); if(error) error.textContent="Este usuário não tem permissão SaaS."; return; } hideGate(); await loadAll(); }catch(err){ console.error(err); if(error) error.textContent="E-mail ou senha inválidos, ou regras do Firestore bloqueando."; }finally{ if(btn){btn.disabled=false;btn.textContent="Entrar";} } }
function openReleaseModal(){ document.querySelector("#saasReleaseOverlay")?.classList.add("show"); document.body.classList.add("modal-open"); }
function closeReleaseModal(){ document.querySelector("#saasReleaseOverlay")?.classList.remove("show"); document.body.classList.remove("modal-open"); }
function fillReleaseForm(item){ document.querySelector("#saasClanTag").value=normalizeTag(item.clanTag||""); document.querySelector("#saasClanName").value=item.clanName||item.name||""; document.querySelector("#saasBuyerEmail").value=item.email||item.buyerEmail||""; document.querySelector("#saasBuyerPhone").value=item.phone||item.buyerPhone||""; document.querySelector("#saasPlan").value=item.plan||"trial"; document.querySelector("#saasStatus").value="released"; openReleaseModal(); }
window.fillSaasReleaseFromRequest=function(encoded){ try{ fillReleaseForm(JSON.parse(decodeURIComponent(encoded))); }catch(e){console.error(e);} };
window.deleteSaasRequest=async function(requestId){ if(!requestId) return; if(!confirm("Excluir esta solicitação?")) return; await deleteDoc(doc(db,"subscriptionRequests",requestId)); await loadAll(); };
window.revokeSaasAccess=async function(clanTag){ const normalized=normalizeTag(clanTag); if(!normalized || !confirm(`Revogar assinatura/liberação do clã ${normalized}?`)) return; await setDoc(doc(db,"saasAccess",normalized),{status:"blocked",allowedOnboarding:false,revokedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true}); await setDoc(doc(db,"clans",normalized),{subscriptionStatus:"blocked",active:false,blockedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true}); await loadAll(); };
window.extendSaasPlan=async function(clanTag, selectId){ const normalized=normalizeTag(clanTag); const plan=document.querySelector(`#${selectId}`)?.value || "basic"; const current=accessCache.find(i=>normalizeTag(i.clanTag||i.id)===normalized) || {}; const currentExp=toDate(current.planExpiresAt); const base=(currentExp && currentExp>new Date()) ? currentExp : new Date(); const expiresAt=addPlanDuration(plan, base); await setDoc(doc(db,"saasAccess",normalized),{plan,planLabel:planLabel(plan),status:"active",allowedOnboarding:true,planExpiresAt:Timestamp.fromDate(expiresAt),updatedAt:serverTimestamp()},{merge:true}); await setDoc(doc(db,"clans",normalized),{plan,planLabel:planLabel(plan),subscriptionStatus:"active",active:true,planExpiresAt:Timestamp.fromDate(expiresAt),updatedAt:serverTimestamp()},{merge:true}); await loadAll(); };
async function loadRequests(){ const snap=await getDocs(query(collection(db,"subscriptionRequests"),orderBy("createdAt","desc"))); requestsCache=snap.docs.map(d=>({id:d.id,...d.data()})); }
async function loadAccess(){ const snap=await getDocs(query(collection(db,"saasAccess"),orderBy("updatedAt","desc"))); accessCache=snap.docs.map(d=>({id:d.id,...d.data()})); }
async function loadAll(){ try{ await Promise.all([loadRequests(), loadAccess()]); renderActiveTab(); }catch(error){ console.error(error); const list=document.querySelector("#saasUnifiedList"); if(list) list.innerHTML=`<div class="saas-row empty">Erro ao carregar dados. Verifique regras do Firestore.</div>`; } }
function renderSales(){ const list=document.querySelector("#saasUnifiedList"); if(!requestsCache.length){ list.innerHTML=`<div class="saas-row empty">Nenhuma venda/solicitação recebida.</div>`; return; } list.innerHTML=requestsCache.map(item=>{ const encoded=encodeURIComponent(JSON.stringify(item)); return `<article class="saas-row saas-request-row"><div><strong>${item.name||item.clanName||item.clanTag||"Solicitação"}</strong><span>${item.clanTag||"sem tag"} • ${item.email||"sem email"} • ${item.phone||"sem WhatsApp"}</span></div><div class="saas-pill plan-${item.plan||"trial"}">${planLabel(item.plan)}</div><div class="saas-actions"><button class="saas-small-action" onclick="fillSaasReleaseFromRequest('${encoded}')">Liberar</button><button class="saas-small-action danger" onclick="deleteSaasRequest('${item.id}')">Excluir</button></div></article>`; }).join(""); }
function renderAccess(bucket){ const list=document.querySelector("#saasUnifiedList"); const items=accessCache.filter(i=>statusBucket(i)===bucket); if(!items.length){ list.innerHTML=`<div class="saas-row empty">Nenhum clã nesta aba.</div>`; return; } list.innerHTML=items.map((item,idx)=>{ const tag=item.clanTag||item.id; const selectId=`planSelect${idx}`; return `<article class="saas-row saas-access-row plan-${item.plan||"trial"}"><div><strong>${item.clanName||tag}</strong><span>${tag} • ${item.buyerEmail||"sem email"}</span></div><div class="saas-pill plan-${item.plan||"trial"}">${item.planLabel||planLabel(item.plan)}</div><small>${item.status||"released"}<br>até ${formatDate(item.planExpiresAt)}</small><div class="saas-plan-edit"><select id="${selectId}"><option value="basic">Básico +1 mês</option><option value="plus">Plus +6 meses</option><option value="premium">Premium +1 ano</option></select><button class="saas-small-action" onclick="extendSaasPlan('${tag}','${selectId}')">Alterar</button></div><button class="saas-small-action danger" onclick="revokeSaasAccess('${tag}')">Revogar</button></article>`; }).join(""); }
function renderActiveTab(){ document.querySelectorAll(".saas-tab").forEach(btn=>btn.classList.toggle("active",btn.dataset.saasTab===activeTab)); const title=document.querySelector("#saasListTitle"); if(title) title.textContent = activeTab==="sales" ? "VENDAS" : activeTab==="trial" ? "TRIAL" : activeTab==="active" ? "ATIVOS" : "EXPIRADOS"; if(activeTab==="sales") renderSales(); else renderAccess(activeTab); }
async function saveAccess(event){ event.preventDefault(); const feedback=document.querySelector("#saasFeedback"); const clanTag=normalizeTag(document.querySelector("#saasClanTag")?.value); const clanName=String(document.querySelector("#saasClanName")?.value||"").trim(); const buyerEmail=String(document.querySelector("#saasBuyerEmail")?.value||"").trim(); const buyerPhone=String(document.querySelector("#saasBuyerPhone")?.value||"").trim(); const plan=document.querySelector("#saasPlan")?.value||"trial"; const status=document.querySelector("#saasStatus")?.value||"released"; if(!clanTag){ feedback.textContent="Informe a tag do clã."; feedback.className="tag-feedback error"; return; } const expiresAt=addPlanDuration(plan); try{ await setDoc(doc(db,"saasAccess",clanTag),{clanTag,clanName,buyerEmail,buyerPhone,plan,planLabel:planLabel(plan),status,allowedOnboarding: status==="released" || status==="active",paymentStatus:"manual",planStartedAt:serverTimestamp(),planExpiresAt:Timestamp.fromDate(expiresAt),onboardingComplete:false,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true}); await setDoc(doc(db,"clans",clanTag),{clanTag,name:clanName,plan,planLabel:planLabel(plan),planExpiresAt:Timestamp.fromDate(expiresAt),subscriptionStatus:status==="released" ? "released" : status,active:status==="active",updatedAt:serverTimestamp()},{merge:true}); feedback.textContent=`${clanTag} liberado como ${planLabel(plan)} até ${expiresAt.toLocaleDateString("pt-BR")}.`; feedback.className="tag-feedback success"; event.currentTarget.reset(); setTimeout(closeReleaseModal,650); await loadAll(); }catch(error){ console.error(error); feedback.textContent="Erro ao liberar assinatura."; feedback.className="tag-feedback error"; } }
document.querySelector("#saasGateBtn")?.addEventListener("click", handleGate);
document.querySelector("#saasGatePassword")?.addEventListener("keydown", e=>{if(e.key==="Enter") handleGate();});
document.querySelector("#saasReleaseForm")?.addEventListener("submit", saveAccess);
document.querySelector("#openNewRelease")?.addEventListener("click", openReleaseModal);
document.querySelector("#closeNewRelease")?.addEventListener("click", closeReleaseModal);
document.querySelector("#saasLogoutBtn")?.addEventListener("click", async()=>{await signOut(auth); showGate();});
document.querySelectorAll(".saas-tab").forEach(btn=>btn.addEventListener("click",()=>{activeTab=btn.dataset.saasTab; renderActiveTab();}));
showGate();
onAuthStateChanged(auth, async user=>{ if(await canAccess(user)){ hideGate(); await loadAll(); } else showGate(); });
