import { parseLocalJSON, findCurrentMemberProfile, saveAvatarEverywhere, getCurrentClanTag } from "./identity.js";
import { db } from "./firebase-config.js";
import { doc, getDoc } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const avatarOptions=["assets/icons/profile-user.svg","assets/avatars/avatar-1.webp","assets/avatars/avatar-2.webp","assets/avatars/avatar-3.webp","assets/avatars/avatar-4.webp","assets/avatars/avatar-5.webp","assets/avatars/avatar-6.webp","assets/avatars/avatar-7.webp","assets/avatars/avatar-8.webp"];
const bgOptions=["premium-bg-royal","premium-bg-gold","premium-bg-blue","premium-bg-purple"];
const clan=parseLocalJSON("topbrs_clan"); let currentPlan="trial", currentPlanData={};
function norm(p){p=String(p||"trial").toLowerCase(); if(["basic","basico","básico"].includes(p))return"basic"; if(p==="plus")return"plus"; if(p==="premium")return"premium"; return"trial"}
function label(p){p=norm(p); return p==="basic"?"Básico":p==="plus"?"Plus":p==="premium"?"Premium":"Trial"}
function dt(v){if(!v)return null;if(v.toDate)return v.toDate();if(v.seconds)return new Date(v.seconds*1000);let d=new Date(v);return isNaN(d)?null:d}
function count(p,ex){let e=dt(ex); if(!e)return"Expiração pendente"; let ms=e-new Date(); if(ms<=0)return"Plano expirado"; let days=Math.floor(ms/86400000),h=Math.floor((ms%86400000)/3600000),m=Math.floor((ms%3600000)/60000),mo=Math.floor(days/30),y=Math.floor(mo/12); p=norm(p); if(p==="trial")return`Expiração: ${days}d ${h}h ${m}min`; if(p==="basic")return`Expiração: ${Math.max(1,mo)} ${Math.max(1,mo)===1?"mês":"meses"}`; if(p==="plus")return`Expiração: ${mo} ${mo===1?"mês":"meses"} e ${days%30} dias`; return`Expiração: ${[y?`${y} ${y===1?"ano":"anos"}`:"",mo%12?`${mo%12} ${mo%12===1?"mês":"meses"}`:""].filter(Boolean).join(" e ")||days+" dias"}`}
async function loadPlan(profile,clanData){let tag=getCurrentClanTag?.()||clanData.clanTag||clanData.tag||"",data={...clanData,...profile}; if(tag){try{let s=await getDoc(doc(db,"clans",tag)); if(s.exists())data={...data,...s.data()}}catch{} try{let s=await getDoc(doc(db,"saasAccess",tag)); if(s.exists())data={...data,...s.data()}}catch{}} return data}
function bgAllowed(i){let p=norm(currentPlan); return p==="premium"||(p==="plus"&&i<2)} function avAllowed(i){let p=norm(currentPlan); if(p==="trial") return i===0; if(p==="basic") return i<2; return p==="premium"||p==="plus"}
function applyBg(){let bg=localStorage.getItem("topbrs_profile_bg")||"premium-bg-royal",hero=document.querySelector(".settings-profile-hero"); hero?.classList.remove(...bgOptions); if(norm(currentPlan)==="premium"||norm(currentPlan)==="plus")hero?.classList.add(bg,"premium-avatar-bg-enabled")}
async function hydrate(){let profile=await findCurrentMemberProfile(),clanData=parseLocalJSON("topbrs_clan"); currentPlanData=await loadPlan(profile,clanData); currentPlan=norm(currentPlanData.plan||"trial"); let userAvatar=document.querySelector("#userAvatar"); userAvatar.src=(currentPlan==="trial"||currentPlan==="basic")?"assets/icons/profile-user.svg":(profile.avatar||localStorage.getItem("topbrs_avatar")||avatarOptions[0]); document.querySelector("#settingsNick").textContent=profile.displayName||profile.nick||profile.name||profile.email||"Usuário"; document.querySelector("#settingsMeta").textContent=`${profile.role||"Admin"} • ${profile.playerTag||"sem tag"}`; document.querySelector("#settingsClan").textContent=currentPlanData.clanName||clanData.name||clan.name||"TopBRS"; document.querySelector("#settingsClanTag").textContent=currentPlanData.clanTag||clanData.clanTag||clanData.tag||clan.tag||"#ABC123"; let cb=document.querySelector("#settingsClanBadge"); if(cb)cb.src=currentPlanData.badge||currentPlanData.badgeSrc||clanData.badge||clanData.badgeSrc||"assets/icons/clan.svg"; let pl=document.querySelector("#settingsPlan"),ex=document.querySelector("#settingsExpire"),card=pl?.closest(".settings-mini-card"); pl.textContent=label(currentPlan); ex.textContent=count(currentPlan,currentPlanData.planExpiresAt||currentPlanData.expiresAt); card?.classList.add(`plan-${currentPlan}`); applyBg()}
function openAvatarPicker(){let overlay=document.querySelector("#avatarPickerOverlay"),grid=document.querySelector("#avatarPickerGrid"),sub=document.querySelector("#avatarPickerSubtitle"),bg=document.querySelector("#premiumBgSelector"); if(sub)sub.textContent="Selecione uma imagem para o seu perfil ou faça UPGRADE de seu plano para liberar todos os avatares e fundos."; grid.innerHTML=avatarOptions.map((src,i)=>{let locked=!avAllowed(i);return`<button type="button" class="avatar-choice ${locked?'locked':''}" data-src="${src}" ${locked?'disabled':''}><img src="${src}" alt="">${locked?'<span class="avatar-lock">🔒</span>':''}</button>`}).join(""); grid.querySelectorAll(".avatar-choice:not(.locked)").forEach(b=>b.onclick=()=>selectAvatar(b.dataset.src)); bg.hidden=false; bg.innerHTML=`<div class="modal-eyebrow">Personalização</div><h3>Fundo do perfil</h3><div class="premium-bg-grid">${bgOptions.map((x,i)=>`<button type="button" class="premium-bg-choice ${x} ${!bgAllowed(i)?'locked':''}" data-bg="${x}" ${!bgAllowed(i)?'disabled':''}>${!bgAllowed(i)?'<span class="avatar-lock">🔒</span>':''}</button>`).join("")}</div>`; bg.querySelectorAll(".premium-bg-choice:not(.locked)").forEach(b=>b.onclick=()=>{localStorage.setItem("topbrs_profile_bg",b.dataset.bg);applyBg()}); document.body.classList.add("modal-open");overlay.classList.add("show")}
function closeAvatarPicker(){document.querySelector("#avatarPickerOverlay").classList.remove("show");document.body.classList.remove("modal-open")}
async function selectAvatar(src){document.querySelector("#userAvatar").src=src;try{await saveAvatarEverywhere(src)}catch{localStorage.setItem("topbrs_avatar",src)}closeAvatarPicker()}
document.querySelector("#openAvatarPicker")?.addEventListener("click",openAvatarPicker);document.querySelector("#closeAvatarPicker")?.addEventListener("click",closeAvatarPicker);document.querySelector("#avatarPickerOverlay")?.addEventListener("click",e=>{if(e.target.id==="avatarPickerOverlay")closeAvatarPicker()});document.querySelector("#logoutSettings")?.addEventListener("click",()=>{if(typeof logoutUser==="function")logoutUser();else location.href="index.html"});hydrate();
function updateSettingsClanBadge(){
  const clanData = parseLocalJSON("topbrs_clan");
  const src = clanData.badge || clanData.badgeSrc || clanData.badgeUrl || "assets/icons/clan.svg";
  document.querySelectorAll(".settings-mini-card.clan-card img,.settings-clan-badge,img[data-settings-clan-badge]").forEach(img=>{
    img.src = src;
    img.onerror = ()=>{ img.src="assets/icons/clan.svg"; };
  });
}
updateSettingsClanBadge();
window.addEventListener("storage", updateSettingsClanBadge);
window.addEventListener("topbrs:clan-badge-updated", updateSettingsClanBadge);
